[package]
name = "otter-launcher"
version = "0.6.5"
edition = "2024"

[dependencies]
regex = "1.11.1"
rustyline = "17.0.2"
rustyline-derive = "0.11.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.9.2"
urlencoding = "2.1.3"
